doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
        'App\Migrations': '%kernel.project_dir%/src/App'
       

    # List of additional migration classes to be loaded, optional
    migrations:
       # - 'App\Migrations\Version20221101054450'





    enable_profiler: false
